# Generated by Django 5.0.14 on 2026-08-03 10:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('donors', '0002_donorprofile_notify_email_donorprofile_notify_push_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='donation_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringDonationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_type', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('time_of_day', models.TimeField()),
                ('pickup_address', models.TextField()),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='donations_d_status_d9ee3d_idx',
            old_name='donations_d_status_9f43a9_idx',
        ),
        migrations.AddField(
            model_name='recurringdonationschedule',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='donors.donorprofile'),
        ),
    ]
